### ISSUE TITLE
when "we back up"? :100:

### ISSUE THREAD

**Issue by calors22** [YsnKey/Leaguemadedev#1]
when will we see another compiled jar? I have the first 3 released (but not the sources, thought it couldn't be DMCA'd, hot oil torture to the t0kio dev's balls), can i have a link to a discord server or some other form of contact?

**Comment by trulyoutstanding** [comment]
Currently no discord servers cus I'm to lazy to make one you can contact me through my discord which is novitaminsneeded and "when will we see another compiled jar" idk but sooner or later there will be a league for 1.20.4 😱🔥🙏💯
