### ISSUE TITLE
how can I download the League Addon

### ISSUE THREAD

**Issue by RaZrad** [YsnKey/Leaguemadedev#3]
there are no files in the "releases", and I don't know how to work with the code.how do I download this addon

**Comment by trulyoutstanding** [comment]
Ill do it later

**Comment by trulyoutstanding** [comment]
But if u can't wait follow this tutorial https://youtu.be/5dEgxdLUQoI?si=Jj7UW6Ac4kpnqkdz but replace the gradle shown in that vid with this https://www.oracle.com/java/technologies/javase/jdk20-archive-downloads.html

**Comment by trulyoutstanding** [comment]
done
