### ISSUE TITLE
Mixin apply failed ~ from mod league -> net.minecraft.class_1297

### ISSUE THREAD

**Issue by calors22** [YsnKey/Leaguemadedev#5]
doesnt launch🙏, only using:

minecraft 1.20.4
meteor 0.5.6 (not dev),
and fabric-loader-0.15.11-1.20.4 (fabric-api-0.96.0 also, but it doesn't seem to change anything)

[latest.log](https://github.com/YsnKey/Leaguemadedev/files/15204934/latest.log)

**Comment by trulyoutstanding** [comment]
I know

**Comment by trulyoutstanding** [comment]
done
