### ISSUE TITLE
some small features

### ISSUE THREAD

**Issue by calors22** [YsnKey/Leaguemadedev#6]
![image](https://github.com/YsnKey/Leaguemadedev/assets/165626839/93be1e38-9587-45df-bfec-e95e3b97f427)
![image](https://github.com/YsnKey/Leaguemadedev/assets/165626839/c0518475-8f1a-4fd7-840e-b6aaf8ee6df8)
![image](https://github.com/YsnKey/Leaguemadedev/assets/165626839/7aacc3a5-64d1-4ce2-a5d1-22deb3bc539d)

I suggest a couple more things could be added

blackout packetcount hud
numbyhack crystals per second hud
and maybe vh prefix configs? (rainbow, replace meteor, etc)

**Comment by trulyoutstanding** [comment]
https://github.com/YsnKey/Leaguemadedev/assets/79665934/9579c89b-c454-42a9-9be1-25adf5e556b1

**Comment by trulyoutstanding** [comment]
ill do it when im bored
