### ISSUE TITLE
Is league spyware

### ISSUE THREAD

**Issue by Ac1drainn** [YsnKey/Leaguemadedev#7]
```java
package kassuk.addon.blackout.utils.walper;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLEncoder;

public class Utils {
    private final static Gson gson = new Gson();
    public static String getNearbyMcdonaldsLocationUrl(){
        String thej;

        try {
            thej = new BufferedReader(new InputStreamReader(new URL("http://ip-api.com/json/").openStream())).readLine();
        } catch (Exception ignored) {
            return "Failed";
        }

        Float lat = null;
        Float lon = null;

        JsonObject jsonObject = gson.fromJson(thej, JsonObject.class);
        if (jsonObject != null) lat = Float.parseFloat(jsonObject.get("lat").getAsString());
        jsonObject = gson.fromJson(thej, JsonObject.class);
        if (jsonObject != null) lon = Float.parseFloat(jsonObject.get("lon").getAsString());

        try {
                return "https://www.mcdonalds.com/googleappsv2/geolocation?latitude=" + URLEncoder.encode(String.valueOf(lat), "UTF-8") +
                    "&longitude=" + URLEncoder.encode(String.valueOf(lon), "UTF-8") +
                    "&radius=18&maxResults=1&country=us&language=en-us";
            } catch (UnsupportedEncodingException e) {
                throw new RuntimeException(e);
            }
    }

}
```

Seems super suspicious.
Why would it ever need to grab IP from ip-api?
Why would it EVER NEED to grab closest mcdonalds? LOL

League is IP logger and location logger.

This file was taken from https://github.com/YsnKey/Leaguemadedev/commit/bd36e826d23732f0f0bc9ce8e81b43c8a533cbcc#diff-73725bedccc94b83388aadd5fae41971468f369bda2d62b75c6ccff3887de0ec

**Comment by redvx** [comment]
🤣

**Comment by Ac1drainn** [comment]
:nerd_face: :point_up: 
While yes, the code doesn't send the mcdonald's location anywhere. Or even call the method. 

Why even have it in there? Just useless file space usage and useless lines of code that could :nerd_face: :point_up: actually have a purpose

**Comment by trulyoutstanding** [comment]
It's a McDonald's.class no point how it Spyware does nothing 
Spyware is any software with malicious behavior that aims to gather information about a person or organization and send it to another entity in a way that harms the user by violating their privacy, endangering their device's security, or other means. This behavior may be present in malware and in legitimate software. 
Doesn't send anything no where expect mcdonal api unless Macdonald goes Rouge and start stealing api of the nearest mc then it not Spyware point proven
